-----------------------------------
-- Setup Database BlazorVacation --
--                               --
-- Run on (tested on):           --     
-- Microsoft SQL Server          --
-----------------------------------

CREATE DATABASE BlazorVacation;

CREATE TABLE EMPLOYEE
(
	ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
	FIRST_NAME NVARCHAR(64) NOT NULL,
	LAST_NAME NVARCHAR(64) NOT NULL,
	TOTAL_ASSIGNED_VACATION_DAYS INT,
);

CREATE TABLE VACATION
(
	ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
	FROM_DATE DATETIME2 NOT NULL,
	TILL_DATE DATETIME2 NOT NULL,
	NOTE NVARCHAR(1024),
	DURATION INT NOT NULL,
	APPROVED BIT NOT NULL,
	SETUP_OUT_OF_OFFICE_EMAIL BIT
);

CREATE TABLE EMPLOYEE_VACATION
(
	EMPLOYEE_ID BIGINT NOT NULL,
	VACATION_ID BIGINT NOT NULL,
	CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID),
	CONSTRAINT FK_VACATION FOREIGN KEY (VACATION_ID) REFERENCES VACATION (ID)
);

CREATE TABLE HOLIDAY
(
	ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
	FROM_DATE DATETIME2 NOT NULL,
	TILL_DATE DATETIME2 NOT NULL,
	NAME NVARCHAR(256) NOT NULL
);

